(deftheme wombat
  "Created 2022-02-15.")

(custom-theme-set-faces
 'wombat
 '(cursor ((((class color) (min-colors 89)) (:background "#cc7878" :underline nil))))
 '(fringe ((((class color) (min-colors 89)) (:background "#2f2f2f" :underline nil))))
 '(highlight ((((class color) (min-colors 89)) (:underline nil :background "#301717" :underline nil))))
 '(region ((t (:background "#444444" :foreground "#f6f3e8" :underline nil))))
 '(secondary-selection ((t (:background "#333366" :foreground "#f6f3e8" :underline nil))))
 '(isearch ((((class color) (min-colors 89)) (:background "#343434" :foreground "#857b6f" :underline nil))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#384048" :foreground "#a0a8b0" :underline nil))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "#444444" :foreground "#f6f3e8" :underline nil))))
 '(mode-line ((((class color) (min-colors 89)) (:background "#141414" :foreground "#857b6f" :underline nil))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#e5786d" :underline nil))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#ddaa6f" :weight bold :underline nil))))
 '(homoglyph ((((class color) (min-colors 89)) (:foreground "#ddaa6f" :weight bold :underline nil))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#e5786d" :underline nil))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#99968b" :underline nil))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#e5786d" :underline nil))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#cae682" :underline nil))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :weight bold :underline nil))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#95e454" :underline nil))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#92a65e" :weight bold :underline nil))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#cae682" :underline nil))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ccaa8f" :underline nil))))
 '(link ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :underline nil))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#e5786d" :underline nil))))
 '(button ((((class color) (min-colors 89)) (:background "#333333" :foreground "#f6f3e8" :underline nil))))
 '(header-line ((((class color) (min-colors 89)) (:background "#303030" :foreground "#e7f6da" :underline nil))))
 '(default ((t (:background "#2f2f2f" :foreground "#f6f3e8" :underline nil))))
 '(marginalia-documentation ((t (:inherit completions-annotations :underline nil)))))

(provide-theme 'wombat)
